package com.cargoacademico.model;
// Generated 09-24-2019 09:07:03 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Aula generated by hbm2java
 */
@Entity
@Table(name = "aula", catalog = "cargo_academico")
public class Aula implements java.io.Serializable {

	private Integer idAula;
	private Edificio edificio;
	private String codigo;
	private Set<AulaEmpleado> aulaEmpleados = new HashSet<AulaEmpleado>(0);

	public Aula() {
	}

	public Aula(Edificio edificio) {
		this.edificio = edificio;
	}

	public Aula(Edificio edificio, String codigo, Set<AulaEmpleado> aulaEmpleados) {
		this.edificio = edificio;
		this.codigo = codigo;
		this.aulaEmpleados = aulaEmpleados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_aula", unique = true, nullable = false)
	public Integer getIdAula() {
		return this.idAula;
	}

	public void setIdAula(Integer idAula) {
		this.idAula = idAula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "edificio", nullable = false)
	public Edificio getEdificio() {
		return this.edificio;
	}

	public void setEdificio(Edificio edificio) {
		this.edificio = edificio;
	}

	@Column(name = "codigo", length = 13)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "aula")
	public Set<AulaEmpleado> getAulaEmpleados() {
		return this.aulaEmpleados;
	}

	public void setAulaEmpleados(Set<AulaEmpleado> aulaEmpleados) {
		this.aulaEmpleados = aulaEmpleados;
	}

}
