package com.cargoacademico.model;
// Generated 09-27-2019 01:09:44 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Campus generated by hbm2java
 */
@Entity
@Table(name = "campus", catalog = "cargo_academico", uniqueConstraints = @UniqueConstraint(columnNames = "coordenadas"))
public class Campus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCampus;
	private Coordenadas coordenadas;
	private Universidad universidad;
	private String campus;
	private String telefono;
	private String ubicacion;
	private Set<Facultad> facultads = new HashSet<Facultad>(0);

	public Campus() {
	}

	public Campus(int idCampus, Universidad universidad) {
		this.idCampus = idCampus;
		this.universidad = universidad;
	}

	public Campus(int idCampus, Coordenadas coordenadas, Universidad universidad, String campus, String telefono,
			String ubicacion, Set<Facultad> facultads) {
		this.idCampus = idCampus;
		this.coordenadas = coordenadas;
		this.universidad = universidad;
		this.campus = campus;
		this.telefono = telefono;
		this.ubicacion = ubicacion;
		this.facultads = facultads;
	}

	@Id

	@Column(name = "id_campus", unique = true, nullable = false)
	public int getIdCampus() {
		return this.idCampus;
	}

	public void setIdCampus(int idCampus) {
		this.idCampus = idCampus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "coordenadas", unique = true)
	public Coordenadas getCoordenadas() {
		return this.coordenadas;
	}

	public void setCoordenadas(Coordenadas coordenadas) {
		this.coordenadas = coordenadas;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "universidad", nullable = false)
	public Universidad getUniversidad() {
		return this.universidad;
	}

	public void setUniversidad(Universidad universidad) {
		this.universidad = universidad;
	}

	@Column(name = "campus", length = 35)
	public String getCampus() {
		return this.campus;
	}

	public void setCampus(String campus) {
		this.campus = campus;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "ubicacion", length = 100)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "campus")
	public Set<Facultad> getFacultads() {
		return this.facultads;
	}

	public void setFacultads(Set<Facultad> facultads) {
		this.facultads = facultads;
	}

}
