package com.cargoacademico.model;
// Generated 09-13-2019 04:06:38 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coordenadas generated by hbm2java
 */
@Entity
@Table(name = "coordenadas", catalog = "cargo_academico")
public class Coordenadas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCoordenada;
	private String latitud;
	private String longitud;
	private String altitud;
	private Set<Facultad> facultads = new HashSet<Facultad>(0);
	private Set<Campus> campuses = new HashSet<Campus>(0);

	public Coordenadas() {
	}

	public Coordenadas(String latitud, String longitud, String altitud) {
		this.latitud = latitud;
		this.longitud = longitud;
		this.altitud = altitud;
	}

	public Coordenadas(String latitud, String longitud, String altitud, Set<Facultad> facultads, Set<Campus> campuses) {
		this.latitud = latitud;
		this.longitud = longitud;
		this.altitud = altitud;
		this.facultads = facultads;
		this.campuses = campuses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_coordenada", unique = true, nullable = false)
	public Integer getIdCoordenada() {
		return this.idCoordenada;
	}

	public void setIdCoordenada(Integer idCoordenada) {
		this.idCoordenada = idCoordenada;
	}

	@Column(name = "latitud", nullable = false, length = 50)
	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	@Column(name = "longitud", nullable = false, length = 50)
	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	@Column(name = "altitud", nullable = false, length = 50)
	public String getAltitud() {
		return this.altitud;
	}

	public void setAltitud(String altitud) {
		this.altitud = altitud;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coordenadas")
	public Set<Facultad> getFacultads() {
		return this.facultads;
	}

	public void setFacultads(Set<Facultad> facultads) {
		this.facultads = facultads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coordenadas")
	public Set<Campus> getCampuses() {
		return this.campuses;
	}

	public void setCampuses(Set<Campus> campuses) {
		this.campuses = campuses;
	}

}
