package com.cargoacademico.model;
// Generated 08-30-2019 02:25:21 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", catalog = "cargo_academico")
public class Departamento implements java.io.Serializable {

	private int idDepartamento;
	private Escuela escuela;
	private String nombre;
	private Set<Materias> materiases = new HashSet<Materias>(0);

	public Departamento() {
	}

	public Departamento(int idDepartamento, Escuela escuela) {
		this.idDepartamento = idDepartamento;
		this.escuela = escuela;
	}

	public Departamento(int idDepartamento, Escuela escuela, String nombre, Set<Materias> materiases) {
		this.idDepartamento = idDepartamento;
		this.escuela = escuela;
		this.nombre = nombre;
		this.materiases = materiases;
	}

	@Id

	@Column(name = "id_departamento", unique = true, nullable = false)
	public int getIdDepartamento() {
		return this.idDepartamento;
	}

	public void setIdDepartamento(int idDepartamento) {
		this.idDepartamento = idDepartamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_escuela", nullable = false)
	public Escuela getEscuela() {
		return this.escuela;
	}

	public void setEscuela(Escuela escuela) {
		this.escuela = escuela;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Materias> getMateriases() {
		return this.materiases;
	}

	public void setMateriases(Set<Materias> materiases) {
		this.materiases = materiases;
	}

}
