package com.cargoacademico.model;
// Generated 09-13-2019 04:06:38 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Edificio generated by hbm2java
 */
@Entity
@Table(name = "edificio", catalog = "cargo_academico")
public class Edificio implements java.io.Serializable {

	private Integer idEdificio;
	private Facultad facultad;
	private String nombreEdificio;
	private Set<Aula> aulas = new HashSet<Aula>(0);

	public Edificio() {
	}

	public Edificio(Facultad facultad, String nombreEdificio) {
		this.facultad = facultad;
		this.nombreEdificio = nombreEdificio;
	}

	public Edificio(Facultad facultad, String nombreEdificio, Set<Aula> aulas) {
		this.facultad = facultad;
		this.nombreEdificio = nombreEdificio;
		this.aulas = aulas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_edificio", unique = true, nullable = false)
	public Integer getIdEdificio() {
		return this.idEdificio;
	}

	public void setIdEdificio(Integer idEdificio) {
		this.idEdificio = idEdificio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facultad", nullable = false)
	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

	@Column(name = "nombre_edificio", nullable = false, length = 45)
	public String getNombreEdificio() {
		return this.nombreEdificio;
	}

	public void setNombreEdificio(String nombreEdificio) {
		this.nombreEdificio = nombreEdificio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "edificio")
	public Set<Aula> getAulas() {
		return this.aulas;
	}

	public void setAulas(Set<Aula> aulas) {
		this.aulas = aulas;
	}

}
