package com.cargoacademico.model;
// Generated 09-24-2019 09:24:18 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EmpleadoMateria generated by hbm2java
 */
@Entity
@Table(name = "empleado_materia", catalog = "cargo_academico", uniqueConstraints = @UniqueConstraint(columnNames = "id_materia"))
public class EmpleadoMateria implements java.io.Serializable {

	private Integer idEmpMate;
	private Empleado empleado;
	private MateriaHorario materiaHorario;
	private Set<AulaEmpleado> aulaEmpleados = new HashSet<AulaEmpleado>(0);

	public EmpleadoMateria() {
	}

	public EmpleadoMateria(Empleado empleado, MateriaHorario materiaHorario) {
		this.empleado = empleado;
		this.materiaHorario = materiaHorario;
	}

	public EmpleadoMateria(Empleado empleado, MateriaHorario materiaHorario, Set<AulaEmpleado> aulaEmpleados) {
		this.empleado = empleado;
		this.materiaHorario = materiaHorario;
		this.aulaEmpleados = aulaEmpleados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_emp_mate", unique = true, nullable = false)
	public Integer getIdEmpMate() {
		return this.idEmpMate;
	}

	public void setIdEmpMate(Integer idEmpMate) {
		this.idEmpMate = idEmpMate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empleado", nullable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_materia", unique = true, nullable = false)
	public MateriaHorario getMateriaHorario() {
		return this.materiaHorario;
	}

	public void setMateriaHorario(MateriaHorario materiaHorario) {
		this.materiaHorario = materiaHorario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleadoMateria")
	public Set<AulaEmpleado> getAulaEmpleados() {
		return this.aulaEmpleados;
	}

	public void setAulaEmpleados(Set<AulaEmpleado> aulaEmpleados) {
		this.aulaEmpleados = aulaEmpleados;
	}

}
