package com.cargoacademico.model;
// Generated 09-26-2019 02:36:50 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado", catalog = "cargo_academico", uniqueConstraints = { @UniqueConstraint(columnNames = "carnet"),
		@UniqueConstraint(columnNames = "dui"), @UniqueConstraint(columnNames = "nit"),
		@UniqueConstraint(columnNames = "usuario") })
public class Empleado implements java.io.Serializable {

	private Integer idEmpleado;
	private TipoDocente tipoDocente;
	private Usuarios usuarios;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private Date fechaNacimiento;
	private String nit;
	private String dui;
	private String carnet;
	private byte[] foto;
	private Set<Facultad> facultads = new HashSet<Facultad>(0);
	private Set<Departamento> departamentos = new HashSet<Departamento>(0);
	private Set<EmpleadoMateria> empleadoMaterias = new HashSet<EmpleadoMateria>(0);

	public Empleado() {
	}

	public Empleado(Usuarios usuarios, String primerNombre, String primerApellido, Date fechaNacimiento, String nit,
			String dui, String carnet) {
		this.usuarios = usuarios;
		this.primerNombre = primerNombre;
		this.primerApellido = primerApellido;
		this.fechaNacimiento = fechaNacimiento;
		this.nit = nit;
		this.dui = dui;
		this.carnet = carnet;
	}

	public Empleado(TipoDocente tipoDocente, Usuarios usuarios, String primerNombre, String segundoNombre,
			String primerApellido, String segundoApellido, Date fechaNacimiento, String nit, String dui, String carnet,
			byte[] foto, Set<Facultad> facultads, Set<Departamento> departamentos,
			Set<EmpleadoMateria> empleadoMaterias) {
		this.tipoDocente = tipoDocente;
		this.usuarios = usuarios;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.fechaNacimiento = fechaNacimiento;
		this.nit = nit;
		this.dui = dui;
		this.carnet = carnet;
		this.foto = foto;
		this.facultads = facultads;
		this.departamentos = departamentos;
		this.empleadoMaterias = empleadoMaterias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_empleado", unique = true, nullable = false)
	public Integer getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(Integer idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_docente")
	public TipoDocente getTipoDocente() {
		return this.tipoDocente;
	}

	public void setTipoDocente(TipoDocente tipoDocente) {
		this.tipoDocente = tipoDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario", unique = true, nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "primer_nombre", nullable = false, length = 25)
	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	@Column(name = "segundo_nombre", length = 25)
	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	@Column(name = "primer_apellido", nullable = false, length = 25)
	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	@Column(name = "segundo_apellido", length = 25)
	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_nacimiento", nullable = false, length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "nit", unique = true, nullable = false, length = 15)
	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	@Column(name = "dui", unique = true, nullable = false, length = 10)
	public String getDui() {
		return this.dui;
	}

	public void setDui(String dui) {
		this.dui = dui;
	}

	@Column(name = "carnet", unique = true, nullable = false, length = 10)
	public String getCarnet() {
		return this.carnet;
	}

	public void setCarnet(String carnet) {
		this.carnet = carnet;
	}

	@Column(name = "foto")
	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleado")
	public Set<Facultad> getFacultads() {
		return this.facultads;
	}

	public void setFacultads(Set<Facultad> facultads) {
		this.facultads = facultads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleado")
	public Set<Departamento> getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set<Departamento> departamentos) {
		this.departamentos = departamentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleado")
	public Set<EmpleadoMateria> getEmpleadoMaterias() {
		return this.empleadoMaterias;
	}

	public void setEmpleadoMaterias(Set<EmpleadoMateria> empleadoMaterias) {
		this.empleadoMaterias = empleadoMaterias;
	}

}
