package com.cargoacademico.model;
// Generated 08-30-2019 02:25:21 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Facultad generated by hbm2java
 */
@Entity
@Table(name = "facultad", catalog = "cargo_academico")
public class Facultad implements java.io.Serializable {

	private int idFacultad;
	private Campus campus;
	private String facultad;
	private String telefono;
	private String ubicacion;
	private Set<Edificio> edificios = new HashSet<Edificio>(0);
	private Set<Escuela> escuelas = new HashSet<Escuela>(0);

	public Facultad() {
	}

	public Facultad(int idFacultad, Campus campus) {
		this.idFacultad = idFacultad;
		this.campus = campus;
	}

	public Facultad(int idFacultad, Campus campus, String facultad, String telefono, String ubicacion,
			Set<Edificio> edificios, Set<Escuela> escuelas) {
		this.idFacultad = idFacultad;
		this.campus = campus;
		this.facultad = facultad;
		this.telefono = telefono;
		this.ubicacion = ubicacion;
		this.edificios = edificios;
		this.escuelas = escuelas;
	}

	@Id

	@Column(name = "id_facultad", unique = true, nullable = false)
	public int getIdFacultad() {
		return this.idFacultad;
	}

	public void setIdFacultad(int idFacultad) {
		this.idFacultad = idFacultad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "campus", nullable = false)
	public Campus getCampus() {
		return this.campus;
	}

	public void setCampus(Campus campus) {
		this.campus = campus;
	}

	@Column(name = "facultad", length = 30)
	public String getFacultad() {
		return this.facultad;
	}

	public void setFacultad(String facultad) {
		this.facultad = facultad;
	}

	@Column(name = "telefono", length = 10)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "ubicacion", length = 60)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facultad")
	public Set<Edificio> getEdificios() {
		return this.edificios;
	}

	public void setEdificios(Set<Edificio> edificios) {
		this.edificios = edificios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facultad")
	public Set<Escuela> getEscuelas() {
		return this.escuelas;
	}

	public void setEscuelas(Set<Escuela> escuelas) {
		this.escuelas = escuelas;
	}

}
