package com.cargoacademico.model;
// Generated 08-30-2019 02:25:21 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Materias generated by hbm2java
 */
@Entity
@Table(name = "materias", catalog = "cargo_academico", uniqueConstraints = @UniqueConstraint(columnNames = "codigo"))
public class Materias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idMateria;
	private Departamento departamento;
	private Materias materias;
	private String materia;
	private String codigo;
	private String ciclo;
	private int unidadValorativa;
	private Set<MateriaHorario> materiaHorarios = new HashSet<MateriaHorario>(0);
	private Set<Materias> materiases = new HashSet<Materias>(0);
	private Set<Temario> temarios = new HashSet<Temario>(0);
	private Set<MateriaCarreraCiclo> materiaCarreraCiclos = new HashSet<MateriaCarreraCiclo>(0);

	public Materias() {
	}

	public Materias(int idMateria, Departamento departamento, String ciclo, int unidadValorativa) {
		this.idMateria = idMateria;
		this.departamento = departamento;
		this.ciclo = ciclo;
		this.unidadValorativa = unidadValorativa;
	}

	public Materias(int idMateria, Departamento departamento, Materias materias, String materia, String codigo,
			String ciclo, int unidadValorativa, Set<MateriaHorario> materiaHorarios, Set<Materias> materiases,
			Set<Temario> temarios, Set<MateriaCarreraCiclo> materiaCarreraCiclos) {
		this.idMateria = idMateria;
		this.departamento = departamento;
		this.materias = materias;
		this.materia = materia;
		this.codigo = codigo;
		this.ciclo = ciclo;
		this.unidadValorativa = unidadValorativa;
		this.materiaHorarios = materiaHorarios;
		this.materiases = materiases;
		this.temarios = temarios;
		this.materiaCarreraCiclos = materiaCarreraCiclos;
	}

	@Id

	@Column(name = "id_materia", unique = true, nullable = false)
	public int getIdMateria() {
		return this.idMateria;
	}

	public void setIdMateria(int idMateria) {
		this.idMateria = idMateria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departamento", nullable = false)
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prerequisito")
	public Materias getMaterias() {
		return this.materias;
	}

	public void setMaterias(Materias materias) {
		this.materias = materias;
	}

	@Column(name = "materia", length = 25)
	public String getMateria() {
		return this.materia;
	}

	public void setMateria(String materia) {
		this.materia = materia;
	}

	@Column(name = "codigo", unique = true, length = 8)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "ciclo", nullable = false, length = 25)
	public String getCiclo() {
		return this.ciclo;
	}

	public void setCiclo(String ciclo) {
		this.ciclo = ciclo;
	}

	@Column(name = "unidad_valorativa", nullable = false)
	public int getUnidadValorativa() {
		return this.unidadValorativa;
	}

	public void setUnidadValorativa(int unidadValorativa) {
		this.unidadValorativa = unidadValorativa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materias")
	public Set<MateriaHorario> getMateriaHorarios() {
		return this.materiaHorarios;
	}

	public void setMateriaHorarios(Set<MateriaHorario> materiaHorarios) {
		this.materiaHorarios = materiaHorarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materias")
	public Set<Materias> getMateriases() {
		return this.materiases;
	}

	public void setMateriases(Set<Materias> materiases) {
		this.materiases = materiases;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materias")
	public Set<Temario> getTemarios() {
		return this.temarios;
	}

	public void setTemarios(Set<Temario> temarios) {
		this.temarios = temarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materias")
	public Set<MateriaCarreraCiclo> getMateriaCarreraCiclos() {
		return this.materiaCarreraCiclos;
	}

	public void setMateriaCarreraCiclos(Set<MateriaCarreraCiclo> materiaCarreraCiclos) {
		this.materiaCarreraCiclos = materiaCarreraCiclos;
	}

}
