package com.cargoacademico.model;
// Generated 09-26-2019 02:36:50 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * MateriaHorario generated by hbm2java
 */
@Entity
@Table(name = "materia_horario", catalog = "cargo_academico", uniqueConstraints = @UniqueConstraint(columnNames = {
		"materia", "horario" }))
public class MateriaHorario implements java.io.Serializable {

	private Integer idMateriaHorario;
	private Materias materias;
	private String horario;
	private Set<EmpleadoMateria> empleadoMaterias = new HashSet<EmpleadoMateria>(0);

	public MateriaHorario() {
	}

	public MateriaHorario(Materias materias) {
		this.materias = materias;
	}

	public MateriaHorario(Materias materias, String horario, Set<EmpleadoMateria> empleadoMaterias) {
		this.materias = materias;
		this.horario = horario;
		this.empleadoMaterias = empleadoMaterias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_materia_horario", unique = true, nullable = false)
	public Integer getIdMateriaHorario() {
		return this.idMateriaHorario;
	}

	public void setIdMateriaHorario(Integer idMateriaHorario) {
		this.idMateriaHorario = idMateriaHorario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "materia", nullable = false)
	public Materias getMaterias() {
		return this.materias;
	}

	public void setMaterias(Materias materias) {
		this.materias = materias;
	}

	@Column(name = "horario", length = 30)
	public String getHorario() {
		return this.horario;
	}

	public void setHorario(String horario) {
		this.horario = horario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materiaHorario")
	public Set<EmpleadoMateria> getEmpleadoMaterias() {
		return this.empleadoMaterias;
	}

	public void setEmpleadoMaterias(Set<EmpleadoMateria> empleadoMaterias) {
		this.empleadoMaterias = empleadoMaterias;
	}

}
