package com.cargoacademico.model;
// Generated 08-30-2019 02:25:21 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Temario generated by hbm2java
 */
@Entity
@Table(name = "temario", catalog = "cargo_academico")
public class Temario implements java.io.Serializable {

	private int idTemario;
	private Materias materias;
	private String nombreTemario;
	private Set<Unidad> unidads = new HashSet<Unidad>(0);

	public Temario() {
	}

	public Temario(int idTemario, Materias materias, String nombreTemario) {
		this.idTemario = idTemario;
		this.materias = materias;
		this.nombreTemario = nombreTemario;
	}

	public Temario(int idTemario, Materias materias, String nombreTemario, Set<Unidad> unidads) {
		this.idTemario = idTemario;
		this.materias = materias;
		this.nombreTemario = nombreTemario;
		this.unidads = unidads;
	}

	@Id

	@Column(name = "id_temario", unique = true, nullable = false)
	public int getIdTemario() {
		return this.idTemario;
	}

	public void setIdTemario(int idTemario) {
		this.idTemario = idTemario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "materia", nullable = false)
	public Materias getMaterias() {
		return this.materias;
	}

	public void setMaterias(Materias materias) {
		this.materias = materias;
	}

	@Column(name = "nombre_temario", nullable = false, length = 45)
	public String getNombreTemario() {
		return this.nombreTemario;
	}

	public void setNombreTemario(String nombreTemario) {
		this.nombreTemario = nombreTemario;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "temario")
	public Set<Unidad> getUnidads() {
		return this.unidads;
	}

	public void setUnidads(Set<Unidad> unidads) {
		this.unidads = unidads;
	}

}
