package com.cargoacademico.model;
// Generated 09-13-2019 04:06:38 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Tema generated by hbm2java
 */
@Entity
@Table(name = "tema", catalog = "cargo_academico")
public class Tema implements java.io.Serializable {

	private Integer idTema;
	private Unidad unidad;
	private String tema;
	private String tiempoTema;

	public Tema() {
	}

	public Tema(Unidad unidad, String tema) {
		this.unidad = unidad;
		this.tema = tema;
	}

	public Tema(Unidad unidad, String tema, String tiempoTema) {
		this.unidad = unidad;
		this.tema = tema;
		this.tiempoTema = tiempoTema;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tema", unique = true, nullable = false)
	public Integer getIdTema() {
		return this.idTema;
	}

	public void setIdTema(Integer idTema) {
		this.idTema = idTema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "unidad", nullable = false)
	public Unidad getUnidad() {
		return this.unidad;
	}

	public void setUnidad(Unidad unidad) {
		this.unidad = unidad;
	}

	@Column(name = "tema", nullable = false, length = 45)
	public String getTema() {
		return this.tema;
	}

	public void setTema(String tema) {
		this.tema = tema;
	}

	@Column(name = "tiempo_tema", length = 25)
	public String getTiempoTema() {
		return this.tiempoTema;
	}

	public void setTiempoTema(String tiempoTema) {
		this.tiempoTema = tiempoTema;
	}

}
