package com.cargoacademico.model;
// Generated 09-26-2019 02:36:50 PM by Hibernate Tools 5.1.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoActividad generated by hbm2java
 */
@Entity
@Table(name = "tipo_actividad", catalog = "cargo_academico")
public class TipoActividad implements java.io.Serializable {

	private Integer idTipoActividad;
	private String descripcion;
	private String actividad;
	private Set<Actividades> actividadeses = new HashSet<Actividades>(0);

	public TipoActividad() {
	}

	public TipoActividad(String actividad) {
		this.actividad = actividad;
	}

	public TipoActividad(String descripcion, String actividad, Set<Actividades> actividadeses) {
		this.descripcion = descripcion;
		this.actividad = actividad;
		this.actividadeses = actividadeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipo_actividad", unique = true, nullable = false)
	public Integer getIdTipoActividad() {
		return this.idTipoActividad;
	}

	public void setIdTipoActividad(Integer idTipoActividad) {
		this.idTipoActividad = idTipoActividad;
	}

	@Column(name = "descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "actividad", nullable = false, length = 45)
	public String getActividad() {
		return this.actividad;
	}

	public void setActividad(String actividad) {
		this.actividad = actividad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoActividad")
	public Set<Actividades> getActividadeses() {
		return this.actividadeses;
	}

	public void setActividadeses(Set<Actividades> actividadeses) {
		this.actividadeses = actividadeses;
	}

}
